routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',['uses'=>'IndexController@execute']);
Auth::routes();

Route::group(['prefix'=>'admin','middleware'=>'auth'],function (){
    //admin
    Route::get('/',['uses'=>'HomeController@index','as'=>'adminIndex']);

    Route::resource('menus','Admin\MenusController');

});

resources/views/admin/custom-menu-items.blade.php
@foreach($items as $item)

		<tr>
			<td>{{ $item->id }}</td>
			<td style="text-align: left;">{{ $paddingLeft }} {!! Html::link(route('menus.index',['menus' => $item->id]),$item->title) !!}</td>
			<td>{{ $item->url() }}</td>
			<td>{{ $item->parent }}</td>

			<td>
			{!! Form::open(['url' => route('menus.destroy',['menus'=> $item->id]),'class'=>'form-horizontal','method'=>'POST']) !!}
												    {{ method_field('DELETE') }}
												    {!! Form::button('Удалить', ['class' => 'btn btn-french-5','type'=>'submit']) !!}
												{!! Form::close() !!}

			</td>
		</tr>		
		 @if($item->hasChildren())
		        
		        @include('admin.custom-menu-items', array('items' => $item->children(),'paddingLeft' => $paddingLeft.'--'))

		 @endif

@endforeach

resources/views/admin/menu.blade.php
@extends('layouts.admin')


@section('content')
    @include('admin.menus_content')
@endsection

resources/views/admin/menus_content.blade.php
<div id="content-page" class="content group">
				            <div class="hentry group">



<div class="short-table white">
	<table style="width: 100%" cellspacing="0" cellpadding="0">
	<thead>
		
		<th>id</th>
		<th>Имя</th>
		<th>Путь</th>
		<th>Родитель</th>
		<th>Действие</th>

	</thead>
	@if($menus)
	
		@include('admin.custom-menu-items', array('items' => $menus->roots(),'paddingLeft' => ''))
		
		
	@endif
	</table>
	</div>
	{!! Html::link(route('menus.create'),'Добавить  пункт',['class' => 'btn btn-the-salmon-dance-3']) !!}
	
</div>
</div>

resources/views/admin/menus_create_content.blade.php
@extends('layouts.admin')


@section('content')

	<div id="content-page" class="content group">
		<div class="hentry group">

			{!! Form::open(['url' => (isset($menu->id)) ? route('menus.update',['menus'=>$menu->id]) : route('menus.store'),'class'=>'contact-form','method'=>'POST','enctype'=>'multipart/form-data']) !!}

			<ul>

				<li class="text-field">
					<label for="name-contact-us">
						<span class="label">Заголовок:</span>
						<br />
						<span class="sublabel">Заголовок пункта</span><br />
					</label>
					<div class="input-prepend"><span class="add-on"><i class="icon-user"></i></span>
						{!! Form::text('title',isset($menu->title) ? $menu->title  : old('title'), ['placeholder'=>'Введите название страницы']) !!}
					</div>
				</li>


				<li class="text-field">
					<label for="name-contact-us">
						<span class="label">Родительский пункт меню:</span>
						<br />
						<span class="sublabel">Родитель:</span><br />
					</label>
					<div class="input-prepend">
						{!! Form::select('parent', $menus, isset($menu->parent) ? $menu->parent : null) !!}
					</div>

				</li>
			</ul>



			<br />

			@if(isset($menu->id))
				<input type="hidden" name="_method" value="PUT">

			@endif
			<ul>
				<li class="submit-button">
					{!! Form::button('Сохранить', ['class' => 'btn btn-the-salmon-dance-3','type'=>'submit']) !!}
				</li>
			</ul>





		</div>
	</div>

			{!! Form::close() !!}





@endsection